apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - port: 80
    name: content
    protocol: TCP
    targetPort: 3000
  selector:
    app: ticketvise-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: ticketvise-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketvise-frontend
  template:
    metadata:
      labels:
        app: ticketvise-frontend
    spec:
      containers:
        - name: ticketvise-frontend
          image: frontend
          ports:
            - containerPort: 3000
