apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - port: 80
    name: content
    protocol: TCP
    targetPort: 80
  selector:
    app: ticketvise-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: ticketvise-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketvise-frontend
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ticketvise-frontend
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: ticketvise-frontend
          image: registry.digitalocean.com/cr-ticketvise/frontend:v2.13.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
