docker_build(
  'frontend',
  context='.',
  dockerfile='Dockerfile.dev',
  live_update=[
    sync('.', '/app')
  ]
)

k8s_yaml('dev.frontend.yaml')

k8s_resource('frontend', labels=['frontend'], links=[link('ivan.ticketvise.com', 'interface')])
