version: '3.7'

services:
  database:
    hostname: database
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    ports:
      - 6000:6000
    environment:
      SQL_ENGINE: django.db.backends.postgresql_psycopg2
      SQL_DATABASE: ticketvise
      SQL_HOST: database

  mail:
    ports:
      - 25:25
      - 465:465
      - 587:587

volumes:
  static:
  media:
  postgres_data:
