version: '3.7'

services:
  web:
    image: ticketvise/backend
    build:
      context: .
    command: >
      sh -c "python manage.py collectstatic --no-input --clear &&
             python manage.py wait_for_database &&
             python manage.py migrate --no-input &&
             python manage.py insert_demo_data &&
             python manage.py runserver 0.0.0.0:6000"
    volumes:
      - ./backend:/backend
    environment:
      DJANGO_SECRET: Welkom01
      EMAIL_PASSWORD: Welikom01
      SQL_USER: ticketvise
      SQL_PASSWORD: Welkom01
      LTI_KEY: LtiKey01
      LTI_SECRET: LtiSecret01

  proxy:
    image: ticketvise/proxy
    build: ./nginx
    ports:
      - 8000:8000
    entrypoint: ""
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
      - ./backend/ticketvise/media:/home/media:ro
      - ./backend/ticketvise/static:/home/static:ro

  database:
    environment:
      POSTGRES_DB: ticketvise
      POSTGRES_USER: ticketvise
      POSTGRES_PASSWORD: Welkom01

  cronjob:
    image: ticketvise/cronjob
    build: ./cronjob
    command: sh -c "env > /etc/environment && cron -f"
