version: '3.7'

services:
  database:
    hostname: database
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    ports:
      - 6000:6000
    environment:
      SQL_ENGINE: django.db.backends.postgresql_psycopg2
      SQL_DATABASE: ticketvise
      SQL_HOST: database

  mail:
    # Quotes around ports are needed, see: https://docs.docker.com/compose/compose-file/#ports.
    ports:
      - "25:25/tcp"
      - "465:465/tcp"
      - "587:587/tcp"

volumes:
  static:
  media:
  postgres_data:
