version: "3.7"

services:
  database:
    hostname: database
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    ports:
      - "6000:6000"
    environment:
      SQL_ENGINE: django.db.backends.postgresql_psycopg2
      SQL_DATABASE: ticketvise
      SQL_HOST: database

  s3:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    entrypoint: sh
    command: -c 'mkdir -p /data/$$S3_BUCKET_NAME && minio server /data --console-address ":9001"'


volumes:
  static:
  media:
  postgres_data:
  minio_data:
