version: '3.7'

services:
  web:
    image: ticketvise/ticketvise/backend:latest
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_database &&
             python manage.py migrate --no-input &&
             python manage.py generate_database &&
             python manage.py runserver 0.0.0.0:6000"
    volumes:
      - ./backend:/backend
    environment:
      - DJANGO_SECRET=Welkom01
      - EMAIL_PASSWORD=Welkom01
      - SQL_USER=ticketvise
      - SQL_PASSWORD=Welkom01
      - LTI_KEY=LtiKey01
      - LTI_SECRET=LtiSecret01

  proxy:
    image: ticketvise/ticketvise/proxy:latest
    build: ./nginx
    ports:
      - 8000:8000
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./backend/ticketvise/media:/home/media:ro
      - ./backend/ticketvise/static:/home/static:ro

  database:
    environment:
      - POSTGRES_DB=ticketvise
      - POSTGRES_USER=ticketvise
      - POSTGRES_PASSWORD=Welkom01