version: "3.7"

services:
  database:
    hostname: database
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    environment:
      POSTGRES_DB: ticketvise
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "5432:5432"

  web:
    image: "ticketvise/backend:sha-${GIT_DIGEST}"
    command: >
      sh -c "python manage.py wait_for_database &&
            "python manage.py configure_s3 &&
             python manage.py migrate --no-input &&
             python manage.py collectstatic --no-input --clear &&
             gunicorn ticketvise.wsgi:application --bind 0.0.0.0:6000"
    ports:
      - "6000:6000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    environment:
      DEBUG: 0
      SEND_MAIL: 1
      DJANGO_SECRET: ${DJANGO_SECRET}
      SMTP_OUTBOUND_PASSWORD: ${EMAIL_PASSWORD}
      SQL_HOST: database
      SQL_DATABASE: ticketvise
      SQL_ENGINE: django.db.backends.postgresql_psycopg2
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      LTI_KEY: ${LTI_KEY}
      LTI_SECRET: ${LTI_SECRET}
      DOMAIN: ${DOMAIN}
      HOST: ${DOMAIN}
      S3_USE_HTTPS: 0
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}

  frontend:
    image: "ticketvise/frontend:sha-${GIT_DIGEST}"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    environment:
      NGINX_DOMAIN: ${DOMAIN}
    ports:
      - "8000:80"

  proxy:
    image: "ticketvise/proxy:sha-${GIT_DIGEST}"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    environment:
      NGINX_DOMAIN: ${DOMAIN}
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - cert_conf:/etc/letsencrypt
      - cert_www:/var/www/certbot

  s3:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    entrypoint: sh
    command: -c 'mkdir -p /data/$$S3_BUCKET_NAME && minio server /data --console-address ":9001"'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    healthcheck:
      test: [ "CMD", "curl", "-f", ${MINIO_ENDPOINT_URL}"/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  certbot:
    image: certbot/certbot
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    volumes:
      - cert_conf:/etc/letsencrypt
      - cert_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  cert_conf:
  cert_www:
  postgres_data:
  minio_data:
