FROM python:3.8-slim

ENV PYTHONUNBUFFERED 1

# APT setup
RUN apt update && apt upgrade -y

# Copy project
RUN mkdir /backend
WORKDIR /backend
COPY . .

# Install dependecies and collect static files
RUN python -m pip install -r requirements.txt

EXPOSE 8000

CMD sh -c "python manage.py wait_for_database;\
python manage.py migrate --no-input;\
python manage.py insert_demo_data;\
python manage.py configure_s3;\
python manage.py runserver 0.0.0.0:8000"
