FROM python:3.8-slim

ENV PYTHONUNBUFFERED 1

# APT setup
RUN apt update && apt upgrade -y

# Copy project
RUN mkdir /backend
WORKDIR /backend
COPY . .

# Install dependecies and collect static files
RUN python -m pip install -r requirements.txt

EXPOSE 8000

CMD ["sh", "./develop.sh"]
