docker_build(
  'backend',
  context='.',
  dockerfile='Dockerfile.dev',
  live_update=[
    sync('.', '/app')
  ]
)

k8s_yaml('dev.backend.yaml')

k8s_resource('backend', port_forwards=8000, labels=['backend'])
