load('ext://uibutton', 'cmd_button', 'location', 'text_input')

docker_build(
  'backend',
  context='.',
  dockerfile='Dockerfile.dev',
  live_update=[
    sync('./ticketvise', '/backend/ticketvise')
  ]
)

k8s_yaml('dev.backend.yaml')

k8s_resource('backend', labels=['backend'], links=[link('ivan.ticketvise.com/api/admin/django', 'admin')])
k8s_resource('database', labels=['backend'])

k8s_resource('s3', port_forwards=9001, labels=['storage'])

cmd_button(name='insert demo data', resource='backend', argv=["kubectl", "exec", "-it", "deploy/backend", "--", "python", "manage.py", "insert_demo_data"])
cmd_button(name='remove data', resource='backend', argv=["kubectl", "exec", "-it", "deploy/backend", "--", "python", "manage.py", "remove_demo_data"])
cmd_button(name='insert admin user', resource='backend', argv=["kubectl", "exec", "-it", "deploy/backend", "--", "python", "manage.py", "insert_admin_user"])
