# Generated by Django 3.0.7 on 2020-08-08 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketvise.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatusEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketvise.TicketEvent')),
                ('status', models.CharField(choices=[('PNDG', 'Pending'), ('ASGD', 'Assigned'), ('ANSD', 'Answered'), ('CLSD', 'Closed')], max_length=8)),
            ],
            bases=('ticketvise.ticketevent',),
        ),
        migrations.CreateModel(
            name='TicketTitleEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketvise.TicketEvent')),
                ('old_title', models.CharField(max_length=100)),
                ('new_title', models.CharField(max_length=100)),
            ],
            bases=('ticketvise.ticketevent',),
        ),
        migrations.CreateModel(
            name='TicketLabelEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketvise.TicketEvent')),
                ('is_added', models.BooleanField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketvise.Label')),
            ],
            bases=('ticketvise.ticketevent',),
        ),
        migrations.CreateModel(
            name='TicketAssigneeEvent',
            fields=[
                ('ticketevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketvise.TicketEvent')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('ticketvise.ticketevent',),
        ),
    ]
