# Generated by Django 3.0.7 on 2020-08-20 20:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment_message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reply_message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
