# Generated by Django 3.1 on 2020-08-26 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0002_auto_20200824_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment_message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reply_message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
