# Generated by Django 3.0.7 on 2020-08-09 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0002_ticketassigneeevent_ticketevent_ticketlabelevent_ticketstatusevent_tickettitleevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
