# Generated by Django 3.1 on 2020-08-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0002_auto_20200824_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='fixed_scheduling_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='scheduling_algorithm',
            field=models.CharField(choices=[('round-robin', 'Round Robin'), ('least-assigned-first', 'Least Assigned First'), ('fixed', 'Fixed')], default='least-assigned-first', max_length=255),
        ),
    ]
