# Generated by Django 3.0.7 on 2020-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0002_auto_20200804_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='inbox',
            name='image',
            field=models.ImageField(default='/static/img/inboxes/default-inbox.png', upload_to='media/img/inboxes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userinbox',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Student'), ('AGENT', 'Teaching Assistant'), ('MANAGER', 'Coordinator')], default='GUEST', max_length=40),
        ),
    ]
