# Generated by Django 3.1 on 2020-08-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0002_auto_20200824_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTicketNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketvise.notification')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_ticket_notifications', to='ticketvise.ticket')),
            ],
            bases=('ticketvise.notification',),
        ),
        migrations.CreateModel(
            name='TicketAssignedNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketvise.notification')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_notifications', to='ticketvise.ticket')),
            ],
            bases=('ticketvise.notification',),
        ),
        migrations.CreateModel(
            name='TicketReminderNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketvise.notification')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_reminder_notifications', to='ticketvise.ticket')),
            ],
            bases=('ticketvise.notification',),
        ),
        migrations.DeleteModel(
            name='TicketStatusChangedNotification',
        ),
    ]
