# Generated by Django 3.1 on 2020-08-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0003_auto_20200827_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_ticket_status_change_app',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification_ticket_status_change_mail',
        ),
        migrations.AddField(
            model_name='user',
            name='notification_assigned_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_assigned_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_ticket_reminder_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_ticket_reminder_mail',
            field=models.BooleanField(default=False),
        ),
    ]
