# Generated by Django 3.1 on 2020-09-11 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticketvise.models.validators
import ticketvise.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0004_auto_20200828_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='color',
            field=models.CharField(default=ticketvise.utils.random_preselected_color, max_length=7, validators=[ticketvise.models.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default=ticketvise.utils.random_preselected_color, max_length=7, validators=[ticketvise.models.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='label',
            name='is_visible_to_guest',
            field=models.BooleanField(default=True),
        ),
    ]
