# Generated by Django 3.1.1 on 2020-10-02 11:46

from django.db import migrations, models
import uuid

from ticketvise.models.ticket import Ticket


def set_initial_message_id(apps, schema_editor):
    for device in Ticket.objects.all():
        device.reply_message_id = uuid.uuid4()
        device.comment_message_id = uuid.uuid4()
        device.save(update_fields=['reply_message_id', 'comment_message_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0006_auto_20200913_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comment_message_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reply_message_id',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(set_initial_message_id),
        migrations.AlterField(
            model_name='ticket',
            name='comment_message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reply_message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
        )
    ]
