# Generated by Django 3.1.1 on 2020-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0006_auto_20200913_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
