# Generated by Django 3.1.2 on 2020-10-25 14:15

from django.db import migrations, models
import ticketvise.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0007_auto_20201021_1745'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ticketvise.models.user.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
