# Generated by Django 3.1.5 on 2021-01-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0012_userinbox_is_assignable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinbox',
            name='give_introduction',
            field=models.BooleanField(default=True),
        ),
    ]
