# Generated by Django 3.1.1 on 2021-02-05 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0013_user_give_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator', to=settings.AUTH_USER_MODEL),
        ),
    ]
