# Generated by Django 3.2.6 on 2021-08-03 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0014_tickettitleevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='email',
            new_name='inbound_email_username',
        ),
        migrations.AddField(
            model_name='inbox',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_port',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_protocol',
            field=models.CharField(choices=[('POP3', 'POP3'), ('IMAP', 'IMAP')], default='IMAP', max_length=4),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_security',
            field=models.CharField(choices=[('NONE', 'None'), ('STARTTLS', 'STARTTLS'), ('TLS', 'TLS')], default='TLS', max_length=8),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_server',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_port',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_security',
            field=models.CharField(choices=[('NONE', 'None'), ('STARTTLS', 'STARTTLS'), ('TLS', 'TLS')], default='TLS', max_length=8),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_server',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_username',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='image',
            field=models.URLField(default='/static/img/inboxes/default-inbox.png'),
        ),
    ]
