# Generated by Django 3.2.6 on 2021-08-05 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0015_auto_20210521_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='email',
        ),
        migrations.AddField(
            model_name='inbox',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_port',
            field=models.IntegerField(default=993, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_protocol',
            field=models.CharField(choices=[('POP3', 'POP3'), ('IMAP', 'IMAP')], default='IMAP', max_length=4),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_security',
            field=models.CharField(choices=[('NONE', 'None'), ('STARTTLS', 'STARTTLS'), ('TLS', 'TLS')], default='TLS', max_length=8),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_server',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_username',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_port',
            field=models.IntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_security',
            field=models.CharField(choices=[('NONE', 'None'), ('STARTTLS', 'STARTTLS'), ('TLS', 'TLS')], default='TLS', max_length=8),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_username',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='image',
            field=models.URLField(default='/static/img/inboxes/default-inbox.png'),
        ),
        migrations.AlterField(
            model_name='inboxsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inboxusersection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='label',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketlabel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketshareduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinbox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
