# Generated by Django 3.2.6 on 2021-08-11 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0016_email_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_pinned',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_public',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pin_initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_initiator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='publish_request_created',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='publish_request_initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_request_initiator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='image',
            field=models.URLField(default='/img/default-inbox.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='inbound_email_protocol',
            field=models.CharField(choices=[('POP3', 'Pop3'), ('IMAP', 'Imap')], default='IMAP', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='/img/default-avatar.png'),
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_removed', models.DateTimeField(default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relationship', to='ticketvise.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_relationship', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ticket')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_tickets',
            field=models.ManyToManyField(related_name='users', through='ticketvise.UserTicket', to='ticketvise.Ticket'),
        ),
    ]
