# Generated by Django 3.2.6 on 2021-08-05 09:11

from ticketvise.models.notification import Notification
from django.db import migrations, models

import uuid

def set_initial_message_id(apps, schema_editor):
    for device in Notification.objects.all():
        device.email_message_id = uuid.uuid4()
        device.save(update_fields=['email_message_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0016_auto_20210805_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comment_message_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='reply_message_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='email_message_id',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(set_initial_message_id),
        migrations.AlterField(
            model_name='notification',
            name='email_message_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True)
        ),
    ]
