# Generated by Django 3.2.6 on 2021-08-18 18:44

from django.db import migrations, models
import ticketvise.models.ticket


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0017_auto_20210811_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(max_length=1000, upload_to=ticketvise.models.ticket.ticket_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='/img/default-avatar.png'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='image',
            field=models.URLField(default='/img/default-inbox.png', max_length=255),
        )
    ]
