# Generated by Django 3.2.6 on 2021-08-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0018_alter_ticketattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_use_oauth2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_use_oauth2',
            field=models.BooleanField(default=False),
        ),
    ]
