# Generated by Django 3.2.6 on 2021-08-31 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0018_alter_ticketattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_condition', to='ticketvise.inbox')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('field_name', models.CharField(max_length=50)),
                ('evaluation_func', models.CharField(max_length=50)),
                ('evaluation_value', models.CharField(max_length=50)),
                ('negation', models.BooleanField(default=False)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketvise.automation')),
            ],
            options={
                'unique_together': {('automation', 'index')},
            },
        ),
    ]
