# Generated by Django 3.2.6 on 2021-09-05 17:49

from django.db import migrations, models
import ticketvise.models.inbox


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0019_rename_image_inbox_image_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='image',
            field=models.ImageField(max_length=1000, null=True, upload_to=ticketvise.models.inbox.inbox_directory_path),
        ),
    ]
