# Generated by Django 3.2.6 on 2021-09-20 10:21

from django.db import migrations, models
import ticketvise.models.inbox


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0020_inbox_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=ticketvise.models.inbox.inbox_directory_path),
        ),
    ]
