# Generated by Django 3.2.6 on 2021-11-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0020_inbox_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='email_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='email_login_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='email_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_use_oauth2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_use_oauth2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='inbound_email_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='inbound_email_server',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='inbound_email_username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='smtp_username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
