# Generated by Django 3.2.6 on 2021-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0020_inbox_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='email_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='email_login_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inbox',
            name='email_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbound_email_use_oauth2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_use_oauth2',
            field=models.BooleanField(default=False),
        ),
    ]
