# Generated by Django 3.2.6 on 2021-12-17 13:07

from django.db import migrations, models
import ticketvise.models.inbox


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0021_auto_20211129_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='image_old',
        ),
        migrations.AlterField(
            model_name='inbox',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=ticketvise.models.inbox.inbox_directory_path),
        ),
    ]
