# Generated by Django 3.2.6 on 2021-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0021_auto_20211004_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='email_login_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
