# Generated by Django 3.2.6 on 2022-02-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0022_auto_20220128_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='code',
            new_name='lti_context_label',
        ),
        migrations.AddField(
            model_name='inbox',
            name='lti_context_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='lti_context_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inbox',
            unique_together={('lti_context_label', 'lti_context_id')},
        ),
    ]
