# Generated by Django 3.2.6 on 2022-01-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0022_auto_20211217_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='smtp_sender',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
