# Generated by Django 3.2.6 on 2022-01-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0023_inbox_smtp_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
