# Generated by Django 4.0.3 on 2022-08-05 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0023_rename_code_inbox_lti_context_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='ticketvise.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
