# Generated by Django 3.2.6 on 2021-11-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0024_commenthelpful'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('action_func', models.CharField(max_length=50)),
                ('action_value', models.CharField(max_length=50)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_condition', to='ticketvise.inbox')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('evaluation_func', models.CharField(choices=[('eq', 'equals'), ('contains', 'contains'), ('gt', 'greater than'), ('ge', 'greater than or equals'), ('lt', 'less than'), ('le', 'less than or equal')], max_length=50)),
                ('evaluation_value', models.CharField(max_length=50)),
                ('negation', models.BooleanField(default=False)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketvise.automation')),
            ],
        ),
    ]
