# Generated by Django 4.0.3 on 2022-03-21 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticketvise.models.inbox


class Migration(migrations.Migration):

    dependencies = [
        ('ticketvise', '0025_automation_automationcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=ticketvise.models.inbox.inbox_directory_path),
        ),
        migrations.CreateModel(
            name='InboxMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to=ticketvise.models.inbox.inbox_directory_path)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_material', to='ticketvise.inbox')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
