# Generated by Django 4.2.7 on 2023-11-18 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticketvise.models.inbox


class Migration(migrations.Migration):

    dependencies = [
        ("ticketvise", "0026_alter_inbox_image_inboxmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="visible_coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visible_coordinator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="inbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automations",
                to="ticketvise.inbox",
            ),
        ),
        migrations.AlterField(
            model_name="automationcondition",
            name="evaluation_func",
            field=models.CharField(
                choices=[
                    ("eq", "equals"),
                    ("contains", "contains"),
                    ("contains_not", "contains not"),
                    ("gt", "greater than"),
                    ("ge", "greater than or equals"),
                    ("lt", "less than"),
                    ("le", "less than or equal"),
                    ("is_set", "is set"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="inbox",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=1000,
                null=True,
                upload_to=ticketvise.models.inbox.inbox_directory_path,
            ),
        ),
    ]
