# Generated by Django 4.2.7 on 2024-05-10 14:42

from django.db import migrations, models
import django.db.models.deletion
import ticketvise.models.inbox


class Migration(migrations.Migration):

    dependencies = [
        (
            "ticketvise",
            "0027_inbox_visible_coordinator_alter_automation_inbox_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LTIClient",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("client_id", models.TextField()),
                ("name", models.TextField()),
                ("auth_login_url", models.TextField()),
                ("auth_token_url", models.TextField()),
                ("auth_audience", models.TextField(null=True)),
                ("key_set_url", models.TextField(null=True)),
                ("key_set", models.TextField(null=True)),
                ("default", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LTIDomain",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("domain", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LTIDeployment",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("deployment_id", models.TextField()),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticketvise.lticlient",
                    ),
                ),
            ],
            options={"unique_together": {("client_id", "deployment_id")},},
        ),
        migrations.AddField(
            model_name="lticlient",
            name="domain_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ticketvise.ltidomain"
            ),
        ),
        migrations.AddField(
            model_name="inbox",
            name="deployment_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ticketvise.ltideployment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lticlient", unique_together={("domain_id", "client_id")},
        ),
    ]
